Core_Project/Models/ErrorViewModel.cs
namespace Core_Project.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Core_Project/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace Core_Project.Controllers
{
    public class AdminController : Controller
    {
        public PartialViewResult PartialSideBar()
        {
            return PartialView();
        }

        public PartialViewResult PartialFooter()
        {
            return PartialView();
        }

        public PartialViewResult PartialNavbar()
        {
            return PartialView();
        }

        public PartialViewResult PartialHeader()
        {
            return PartialView();
        }

        public PartialViewResult PartialScript()
        {
            return PartialView();
        }

        
    }
}

Core_Project/Controllers/ExperienceController.cs
using BussinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Core_Project.Controllers
{
    public class ExperienceController : Controller
    {
        private ExperienceManager experienceManager = new ExperienceManager(new EfExperienceDal());
        public IActionResult Index()
        {
            ViewBag.deger1 = "Deneyim Listesi";
            ViewBag.deger2 = "Deneyimler";
            ViewBag.deger3 = "Deneyim Listesi";

            var values = experienceManager.TGetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddExperience()
        {
            ViewBag.deger1 = "Deneyim Ekleme";
            ViewBag.deger2 = "Deneyimler";
            ViewBag.deger3 = "Deneyim Ekleme";
            return View();
        }

        [HttpPost]
        public IActionResult AddExperience(Experience experience)
        {
            experienceManager.TAdd(experience);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteExperience(int id)
        {
            var values = experienceManager.TGetById(id);
            experienceManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult UpdateExperience(int id)
        {
            ViewBag.deger1 = "Güncelle";
            ViewBag.deger2 = "Deneyimler";
            ViewBag.deger3 = "Deneyim Güncelleme";
            var values = experienceManager.TGetById(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult UpdateExperience(Experience experience)
        {
            experienceManager.TUpdate(experience);
            return RedirectToAction("Index");
        }
    }
}

Core_Project/Controllers/FeatureController.cs
using Microsoft.AspNetCore.Mvc;

namespace Core_Project.Controllers
{
    public class FeatureController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Core_Project/Controllers/HomeController.cs
using Core_Project.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Core_Project.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Core_Project/Controllers/HomePageController.cs
using Microsoft.AspNetCore.Mvc;

namespace Core_Project.Controllers
{
    public class HomePageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


        public PartialViewResult HeaderPartial()
        {
            return PartialView();
        }

        public PartialViewResult NavbarPartial()
        {
            return PartialView();
        }
    }
}

Core_Project/Controllers/SendMessageController.cs
using BussinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Core_Project.Controllers
{
    public class SendMessageController : Controller
    {
        private MessageManager messageManager = new MessageManager(new EfMessageDal());

        [HttpPost]
        public IActionResult Index(Message message)
        {
            message.Date = DateTime.Now.ToLocalTime();
            message.Status = true;
            messageManager.TAdd(message);
            return Redirect("/HomePage/Index#contact");
        }
    }
}

Core_Project/Controllers/SkillController.cs
using BussinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Core_Project.Controllers
{
    public class SkillController : Controller
    {
        private SkillManager skillManager = new SkillManager(new EfSkillDal());
        public IActionResult Index()
        {
            ViewBag.deger1 = "Yetenek Listesi";
            ViewBag.deger2 = "Yetenekler";
            ViewBag.deger3  = "Yetenek Listesi";
            var values = skillManager.TGetList();
            return View(values);
        }

        [HttpGet]
        public IActionResult AddSkill()
        {
            ViewBag.deger1 = "Yetenek Ekleme";
            ViewBag.deger2 = "Yetenekler";
            ViewBag.deger3 = "Yetenek Ekleme";
            return View();
        }

        [HttpPost]
        public IActionResult AddSkill(Skill skill)
        {
            skillManager.TAdd(skill);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteSkill(int id)
        {
            var values = skillManager.TGetById(id);
            skillManager.TDelete(values);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult UpdateSkill(int id)
        {
            ViewBag.deger1 = "Güncelle";
            ViewBag.deger2 = "Yetenekler";
            ViewBag.deger3 = "Yetenek Güncelleme";
            var values = skillManager.TGetById(id);
            return View(values);
        }

        [HttpPost]
        public IActionResult UpdateSkill(Skill skill)
        {
            skillManager.TUpdate(skill);
            return RedirectToAction("Index");
        }
    }
}

Core_Project/Views/Admin/PartialFooter.cshtml
<br/><br/>
<footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
        <div class="col-lg-6">
            <div class="copyright text-center  text-lg-left  text-muted">
                &copy; 2020 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
            </div>
        </div>
        <div class="col-lg-6">
            <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                <li class="nav-item">
                    <a href="https://www.creative-tim.com" class="nav-link" target="_blank">Creative Tim</a>
                </li>
                <li class="nav-item">
                    <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
                </li>
                <li class="nav-item">
                    <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
                </li>
                <li class="nav-item">
                    <a href="https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md" class="nav-link" target="_blank">MIT License</a>
                </li>
            </ul>
        </div>
    </div>
</footer>
<br/> 

Core_Project/Views/Admin/PartialHeader.cshtml
<div class="header bg-primary pb-6">
        

    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <h6 class="h2 text-white d-inline-block mb-0">@ViewBag.deger1</h6>
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#">@ViewBag.deger2</a></li>
                            <li class="breadcrumb-item active" aria-current="page">@ViewBag.deger3</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div> 
</div>
<br/>

Core_Project/Views/Admin/PartialScript.cshtml
<!-- Core -->
<script src="/argon-dashboard-master/assets/vendor/jquery/dist/jquery.min.js"></script>
<script src="/argon-dashboard-master/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="/argon-dashboard-master/assets/vendor/js-cookie/js.cookie.js"></script>
<script src="/argon-dashboard-master/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
<script src="/argon-dashboard-master/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>
<!-- Optional JS -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
<!-- Argon JS -->
<script src="/argon-dashboard-master/assets/js/argon.js?v=1.2.0"></script>

Core_Project/Views/Admin/PartialSideBar.cshtml
<div class="navbar-inner">
    <!-- Collapse -->
    <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/argon-dashboard-master/examples/dashboard.html">
                    <i class="ni ni-tv-2 text-primary"></i>
                    <span class="nav-link-text">Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/argon-dashboard-master/examples/icons.html">
                    <i class="ni ni-planet text-orange"></i>
                    <span class="nav-link-text">Öne Çıkanlar</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="/Skill/Index">
                    <i class="ni ni-pin-3 text-primary"></i>
                    <span class="nav-link-text">Yetenekler</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/argon-dashboard-master/examples/profile.html">
                    <i class="ni ni-single-02 text-yellow"></i>
                    <span class="nav-link-text">Hakkımda</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/argon-dashboard-master/examples/tables.html">
                    <i class="ni ni-bullet-list-67 text-default"></i>
                    <span class="nav-link-text">Hizmetler</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/argon-dashboard-master/examples/login.html">
                    <i class="ni ni-key-25 text-info"></i>
                    <span class="nav-link-text">Projeler</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/Experience/Index/">
                    <i class="ni ni-circle-08 text-pink"></i>
                    <span class="nav-link-text">Deneyimler</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/argon-dashboard-master/examples/upgrade.html">
                    <i class="ni ni-send text-dark"></i>
                    <span class="nav-link-text">Referanslar</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/argon-dashboard-master/examples/upgrade.html">
                    <i class="ni ni-send text-dark"></i>
                    <span class="nav-link-text">İletişim</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/argon-dashboard-master/examples/upgrade.html">
                    <i class="ni ni-send text-dark"></i>
                    <span class="nav-link-text">Mesajlar</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/argon-dashboard-master/examples/upgrade.html">
                    <i class="ni ni-send text-dark"></i>
                    <span class="nav-link-text">Ayarlar</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/argon-dashboard-master/examples/upgrade.html">
                    <i class="ni ni-send text-dark"></i>
                    <span class="nav-link-text">İstatistikler</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/argon-dashboard-master/examples/upgrade.html">
                    <i class="ni ni-send text-dark"></i>
                    <span class="nav-link-text">Çıkış Yap</span>
                </a>
            </li>
        </ul>
    
    </div>
</div>

Core_Project/Views/Experience/AddExperience.cshtml
@model EntityLayer.Concrete.Experience
@{
    ViewData["Title"] = "AddExperience";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
            <div class="card" style="padding-left:20px; padding-right:20px;">
                <!-- Card header -->
                <div class="card-header border-0">
                    <h3 class="mb-0">Deneyim Ekle</h3>
                </div>
                @using (Html.BeginForm("AddExperience", "Experience", FormMethod.Post))
                {
                    @Html.HiddenFor(e=>e.Id)
                    <label>Deneyim Başlığı</label>
                    @Html.TextBoxFor(e=>e.Name , new {@class="form-control"})

                    <label>Deneyim Tarihi</label>
                    @Html.TextBoxFor(e=>e.Date , new {@class="form-control"})
                    <label>Resim Yolu</label>
                    @Html.TextBoxFor(e => e.ImageUrl, new { @class = "form-control" })
                    <label>Açıklama</label>
                    @Html.TextAreaFor(e=>e.Description,10,3, new {@class="form-control"})
                    <br/>
                    <button class="btn btn-primary">Ekle</button>
                }
            </div>
           
        </div>
    </div>
</div>

Core_Project/Views/Experience/Index.cshtml
@using EntityLayer.Concrete
@model List<Experience>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Index</h1>
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
            <div class="card">
                <!-- Card header -->
                <div class="card-header border-0">
                    <h3 class="mb-0">Deneyimlerim</h3>
                </div>
                <!-- Light table -->
                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col" class="sort" data-sort="name">#</th>
                                <th scope="col" class="sort" data-sort="budget">BAŞLIK</th>
                                <th scope="col" class="sort" data-sort="status">TARİH</th>
                                <th scope="col" class="sort" data-sort="status">SİL</th>
                                <th scope="col" class="sort" data-sort="completion">DÜZENLE</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.Name</td>
                                    <td>@item.Date</td>
                                    <td><a href="/Experience/DeleteExperience/@item.Id" class="btn btn-primary">Sil</a></td>
                                    <td><a href="/Experience/UpdateExperience/@item.Id" class="btn btn-secondary">Düzenle</a></td>
                                </tr>


                            }

                        </tbody>

                    </table>
                </div>

            </div>
            <a href="/Experience/AddExperience/" class="btn btn-success">Yeni Deneyim Ekle</a>
        </div>
    </div>

</div>

Core_Project/Views/Experience/UpdateExperience.cshtml
@model EntityLayer.Concrete.Experience
@{
    ViewData["Title"] = "UpdateExperience";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
            <div class="card" style="padding-left:20px; padding-right:20px;">
                <!-- Card header -->
                <div class="card-header border-0">
                    <h3 class="mb-0">Deneyimleri Düzenle</h3>
                </div>
                @using (Html.BeginForm("UpdateExperience", "Experience", FormMethod.Post))
                {
                    @Html.HiddenFor(e=>e.Id)
                    <label>Başlık</label>
                    @Html.TextBoxFor(e=>e.Name , new {@class="form-control"})

                    <label>Deneyim Tarihi</label>
                    @Html.TextBoxFor(e=>e.Date , new {@class="form-control"})
                    <label>Resim Yolu </label>
                    @Html.TextBoxFor(e=>e.ImageUrl , new {@class="form-control"})

                    <label>Açıklama </label>
                    @Html.TextBoxFor(e=>e.Description , new {@class="form-control"})
                    <br/>
                    <button class="btn btn-primary">Kaydet</button>
                }
            </div>
            
        </div>
    </div>
</div>

Core_Project/Views/Feature/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
@* <h1>Burası content alanıdır.</h1> *@
</div>

Core_Project/Views/Shared/Components/AboutList/Default.cshtml
@using EntityLayer.Concrete
@model List<About>

<div class="section pt-4 px-3 px-lg-4" id="about">
    <div class="container-narrow">
        <div class="row">
            @foreach (var item in Model)
            {
            <div class="col-md-6">

                <h2 class="h4 my-2">@item.Title</h2>
                <p>@item.Description</p>
                <div class="row mt-3">
                    <div class="col-sm-2">
                        <div class="pb-1">Yaş:</div>
                    </div>
                    <div class="col-sm-10">
                        <div class="pb-1 fw-bolder">@item.Age</div>
                    </div>
                    <div class="col-sm-2">
                        <div class="pb-1">Mail:</div>
                    </div>
                    <div class="col-sm-10">
                        <div class="pb-1 fw-bolder">@item.Mail</div>
                    </div>

                    <div class="col-sm-2">
                        <div class="pb-1">Telefon:</div>
                    </div>
                    <div class="col-sm-10">
                        <div class="pb-1 fw-bolder">@item.Phone</div>
                    </div>
                    <div class="col-sm-2">
                        <div class="pb-1">Adres:</div>
                    </div>
                    <div class="col-sm-10">
                        <div class="pb-1 fw-bolder">@item.Address</div>
                    </div>


                </div>

            </div>
            <div class="col-md-5 offset-md-1" data-aos="fade-left" data-aos-delay="100"><img class="avatar img-fluid mt-2" src="@item.ImageUrl" width="400" height="400" alt="Walter Patterson"/></div>

            }
        </div>
    </div>
</div>

Core_Project/Views/Shared/Components/ContactList/Default.cshtml
@using EntityLayer.Concrete
@model List<Contact>

  
            <div class="col-md-6" data-aos="fade-left" data-aos-delay="300">
                @foreach (var item in Model)
                {
                    <div class="mt-3 px-1">
                        <div class="h5">@item.Title</div>
                        <p>@item.Description</p>

                    </div>
                    <div class="mt-53 px-1">
                        <div class="row">
                            <div class="col-sm-2">
                                <div class="pb-1">Email:</div>
                            </div>
                            <div class="col-sm-10">
                                <div class="pb-1 fw-bolder">@item.Mail</div>
                            </div>
                            
                            <div class="col-sm-2">
                                <div class="pb-1">Phone:</div>
                            </div>
                            <div class="col-sm-10">
                                <div class="pb-1 fw-bolder">@item.Phone</div>
                            </div>
                        </div>
                    </div>
                }
            </div>
       

Core_Project/Views/Shared/Components/FeatureList/Default.cshtml
@using EntityLayer.Concrete
@model List<Feature>

<header>
    <div class="cover bg-light">
        <div class="container px-3">
            <div class="row">
                <div class="col-lg-6 p-2"><img class="img-fluid" src="~/Template/images/illustrations/hello3.svg" alt="hello" /></div>
                <div class="col-lg-6">
                    @foreach (var item in Model)
                    {
                        <div class="mt-5">
                            <p class="lead text-uppercase mb-1">@item.Header</p>
                            <h1 class="intro-title marker" data-aos="fade-left" data-aos-delay="50">@item.Name</h1>
                            <p class="lead fw-normal mt-3" data-aos="fade-up" data-aos-delay="100">@item.Title</p>
                            <div class="social-nav" data-aos="fade-up" data-aos-delay="200">
                                <nav role="navigation">
                                    <ul class="nav justify-content-left">
                                        <li class="nav-item"><a class="nav-link" href="https://twitter.com/templateflip" title="Twitter"><i class="fab fa-twitter"></i><span class="menu-title sr-only">Twitter</span></a></li>
                                        <li class="nav-item"><a class="nav-link" href="https://www.facebook.com/templateflip" title="Facebook"><i class="fab fa-facebook"></i><span class="menu-title sr-only">Facebook</span></a></li>
                                        <li class="nav-item"><a class="nav-link" href="https://www.instagram.com/templateflip" title="Instagram"><i class="fab fa-instagram"></i><span class="menu-title sr-only">Instagram</span></a></li>
                                        <li class="nav-item"><a class="nav-link" href="https://www.linkedin.com/" title="LinkedIn"><i class="fab fa-linkedin"></i><span class="menu-title sr-only">LinkedIn</span></a></li>
                                        <li class="nav-item"><a class="nav-link" href="https://www.behance.net/templateflip" title="Behance"><i class="fab fa-behance"></i><span class="menu-title sr-only">Behance</span></a></li>
                                    </ul>
                                </nav>
                            </div>
                            <div class="mt-3" data-aos="fade-up" data-aos-delay="200"><a class="btn btn-primary shadow-sm mt-1 hover-effect" href="#contact">Bana Ulaşın <i class="fas fa-arrow-right"></i></a></div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="wave-bg"></div>
</header>

Core_Project/Views/Shared/Components/PortfolioList/Default.cshtml
@using EntityLayer.Concrete
@model List<Portfolio>


<div class="section px-2 px-lg-4 pt-5" id="portfolio">
    <div class="container">
        <div class="text-center mb-5">
            <h2 class="marker marker-center">Projelerim </h2>
        </div>
        <div class="grid bp-gallery pb-3" data-aos="zoom-in-up" data-aos-delay="100">
            <div class="grid-sizer"></div>
            @foreach (var item in Model)
            {
                <div class="grid-item">
                    <a href="https://github.com/elifpolatt/">
                        <figure class="portfolio-item">
                            <img src="@item.ImageUrl" data-bp="@item.ImageUrlSlider" />
                        
                            <figcaption>
                                <h4 class="h5 mb-0">@item.Name</h4>
                                <div>@item.ProjectUrl</div>
                            </figcaption>
                        </figure>
                    </a>
                </div>
            }
        </div>
    </div>
</div>

Core_Project/Views/Shared/Components/SendMessage/Default.cshtml
@using EntityLayer.Concrete
@model List<Message>

<div class="col-md-6" data-aos="zoom-in" data-aos-delay="100">
    <div class="bg-light my-2 p-3 pt-2">
        <form method="POST" asp-controller="SendMessage" asp-action="Index">
            <div class="form-group my-2">
                <label for="name" class="form-label fw-bolder">Adınız</label>
                <input class="form-control" type="text" id="name" name="Name" required>
            </div>
            <div class="form-group my-2">
                <label for="email" class="form-label fw-bolder">Mail Adresiniz</label>
                <input class="form-control" type="email" id="email" name="Mail" required>
            </div>
            <div class="form-group my-2">
                <label for="message" class="form-label fw-bolder">Mesajınız</label>
                <textarea class="form-control" style="resize: none;" id="message" name="Content" rows="4" required></textarea>
            </div>
            <button class="btn btn-primary mt-2" type="submit">Gönder</button>
        </form>
    </div>
</div>

Core_Project/Views/Shared/Components/ServiceList/Default.cshtml
@using EntityLayer.Concrete
@model List<Service>

<div class="section px-3 px-lg-4 pt-5" id="services">
    <div class="container-narrow">
        <div class="text-center mb-5">
            <h2 class="marker marker-center">Yeteneklerim</h2>
        </div>
        <div class="text-center">
            <p class="mx-auto mb-3" style="max-width:600px"> I offer services fit for any website or app. I can quickly maximize timely deliverables for real-time schemas.</p>
        </div>
        
        
            <div class="row py-3">
                @foreach (var item in Model)
                {
                    <div class="col-md-3 text-center" data-aos="fade-up" data-aos-delay="100">
                        <img class="mb-2" src="@item.ImageUrl" width="96" height="96" alt="web design"/>
                        <div class="h5">@item.Title</div>
                    </div>
                }
               
            </div>
        
    </div>
</div>

Core_Project/Views/Shared/Components/SkillList/Default.cshtml
@using EntityLayer.Concrete
@model List<Skill>


<div class="section px-3 px-lg-4 pt-5" id="skills">
    <div class="container-narrow">
        <div class="text-center mb-5">
            <h2 class="marker marker-center">Yeteneklerim</h2>
        </div>
        <div class="text-center">
            <p class="mx-auto mb-3" style="max-width:600px">Bildiğim ve üzerine projeler geliştirdiğim programlama dilleri aşağıdaki gibidir. Yeni şeyler öğrenme konusunda çok istekli ve meraklıyımdır.</p>
        </div>
        <div class="bg-light p-3">
            <div class="row">
                <div class="col-md-12">
                    @foreach (var item in Model)
                    {
                        <div class="py-1">
                            <div class="d-flex text-small fw-bolder"><span class="me-auto">@item.Title</span><span>@item.Value%</span></div>
                            <div class="progress my-1">
                                <div class="progress-bar bg-primary" role="progressbar" data-aos="zoom-in-right" data-aos-delay="100" data-aos-anchor=".skills-section" style="width: @item.Value%" aria-valuenow=" @item.Value" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                    }
                   
                </div>
            </div>
        </div>
    </div>
</div>